### Задание 1

Найти угол между векторами-фильмами `"Ярость"` и `"12 лет рабства"`. Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [1]:
import numpy as np

In [2]:
film_1 = np.array([0, 0, 0, 0, 1, 0])      # Игра в имитацию
film_2 = np.array([0, 1, 0, 1, 0, 0])      # Ярость
film_3 = np.array([0, 0, 1, 1, 1, 0])      # 12 лет рабства
film_4 = np.array([1, 0, 0, 1, 0, 1])      # Однажды в Голливуде

In [3]:
# Вычислим угол между векторами-фильмами
np.rad2deg(np.arccos(np.dot(film_2, film_3) / (np.linalg.norm(film_2) * np.linalg.norm(film_3))))

65.90515744788931

### Задание 2

Вычислить с помощью `Python` значение первой производной для функции $8x(x+3)^2$ в точке $x=1$.

In [6]:
import sympy as sym

In [9]:
# Определим 'x' как аналитический параметр
x = sym.Symbol('x')

In [12]:
# Найдём первую производную для заданной функции
res = sym.diff(8 * x * (x + 3)**2, x)
res

8*x*(2*x + 6) + 8*(x + 3)**2

In [13]:
# Вычислим значение производной в точке x=1
res.subs(x, 1)

192

### Задание 3

Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы.  
Умножить вектор [1, 2, 3, 4] на полученную матрицу.

In [14]:
# Создадим матрицу из векторов фильмов
A = np.array([film_1, film_2, film_3, film_4])
A

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [17]:
# Создадим вектор
A1 = np.array([1, 2, 3, 4])
A1

array([1, 2, 3, 4])

In [27]:
# Выполним умножение матриц
A1 @ A

array([4, 2, 3, 9, 4, 4])